### ISSUE TITLE
Not offering options to the user to control data usage

### ISSUE THREAD

**Issue by amazuerar** [H21lab/Earth-Viewer#3]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within Android apps. As result of this we identified some code locations that might have network related problems.

In this case, we address the code locations that are related to a potential issue concerning not offering to the users control over their usage of network resources. If your application performs network operations, you should provide user settings that allow users to control your app’s data habits, such as how often your app syncs data, whether to perform uploads/downloads only when on Wi-Fi, or whether to use data while roaming.

In order to address this issue we recommend:

1. The declaration of an intent filter for the `ACTION_MANAGE_NETWORK_USAGE` action to indicate that your application defines an activity that offers options to control data usage. `ACTION_MANAGE_NETWORK_USAGE` shows settings for managing the network data usage of a specific application.

2. https://developer.android.com/training/basics/network-ops/managing#implement-preference-activity

**Potential Code Location not offering options to the user to control data usage**

Within the Manifest one can notice the usage of `android.permission.INTERNET` but no `ACTION_MANAGE_NETWORK_USAGE`

https://github.com/H21lab/Earth-Viewer/blob/d02841501b91da2fede56f7baaf68c8fedafdeb9/app/src/main/AndroidManifest.xml#L10

**Comment by H21lab** [comment]
This seems to be not relevant here. The data usage in this application is triggered only after user explicitly request the specific data set.

**Comment by amazuerar** [comment]
Greetings @H21lab 

I appreciate your quick reply and your feedback, it is helpful in order to refine the tool and our heuristics 😄  
We have identified a couple more of potential issues, feel free to contact me if you are interested! Once again, thanks!
