### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by VasilisKos** [H21lab/Earth-Viewer#6]
1. Add an index of the colors used, like in the CCI website. At the bottom of the screen would be handy.
2. Add Aurora activity map.

**Comment by H21lab** [comment]
Thank you for your suggestion.

1. Color index for CCI data has been added to the latest release.
2. For Aurora activity map - I did not find some good data source which would be easy to implement into current code. Any reference to this?

**Comment by VasilisKos** [comment]
> Thank you for your suggestion.
> 
> 1. Color index for CCI data has been added to the latest release.
> 2. For Aurora activity map - I did not find some good data source which would be easy to implement into current code. Any reference to this?

1. So, I guess you'll update the app in Google Play too, right?
2. Here are the most accurate ones. Not, sure if you can use them:
https://www.swpc.noaa.gov/products/aurora-30-minute-forecast

**Comment by H21lab** [comment]
1. Yes, the app will be updated soon.
2. There are folders: https://services.swpc.noaa.gov/images/animations/ovation/north/ and https://services.swpc.noaa.gov/images/animations/ovation/south/. These can be possibly used. Thank you for pointing me to this, I will consider it.

**Comment by H21lab** [comment]
2. NOAA Aurora data set has been added. It will be published on the Google Play soon.
