### ISSUE TITLE
Aurora images issue

### ISSUE THREAD

**Issue by VasilisKos** [H21lab/Earth-Viewer#7]
Can this be fixed? Some way to exclude the text of the images?

![Screenshot_20230318-073130](https://user-images.githubusercontent.com/12777771/226085943-f2cb44b5-7f72-4b41-9c3d-4f641731223b.png)
![Screenshot_20230318-073106](https://user-images.githubusercontent.com/12777771/226085945-dd57a6c4-1f6c-4591-9d48-fe2c471c2fdd.png)

**Comment by H21lab** [comment]
Maybe I will try to improve it later. If you check the original images https://services.swpc.noaa.gov/images/animations/ovation/north/, you will see that the labels and text is over Earth. This is causing it. The possible way to remove it is to do some post processing, maybe to suppress yellow color or to cut it somehow, but this can cause other artifacts. Additionally the image from the source contained rotated Earth so it is not perfectly mapped, but only estimated.

**Comment by VasilisKos** [comment]
Ok. You know better. That's why I asked. 😉

**Comment by H21lab** [comment]
The images have been cropped to exclude the text in the latest release.
