### ISSUE TITLE
Application data

### ISSUE THREAD

**Issue by VasilisKos** [H21lab/Earth-Viewer#8]
I've noticed that, the more data you download in the app, the more they are stored in the apps data, not the cache. So, I guess that the app size will increase significantly by time. Is that data deleted after they're expired? I think they should be stored in the app's cache.

**Comment by H21lab** [comment]
Is this causing any issue on your device? In reloadTexture there is deletion of old files (https://github.com/H21lab/Earth-Viewer/blob/master/app/src/main/java/mobile/application/forfree/earth/DownloadTextures.java#L135).

**Comment by VasilisKos** [comment]
Well, I can't say. I'm not a developer, so can't test it. I haven't noticed if it happens when it downloads newer files over old ones. I'll check and tell you.

**Comment by H21lab** [comment]
I considered this valid comment and thank you for reporting this. The downloaded images are stored in cache in the latest version.
